# Generated by Django 3.2.5 on 2024-04-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('movie_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.movie')),
            ],
            options={
                'db_table': 'tb_movie_ranking',
            },
        ),
    ]
