# Generated by Django 3.2.5 on 2024-04-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_movie_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_ranking',
            old_name='rank',
            new_name='rank_score',
        ),
        migrations.AlterModelTable(
            name='movie_rating',
            table='tb_movie_rating',
        ),
    ]
