# Generated by Django 3.2.5 on 2024-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20240408_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_ranking',
            name='rank_score',
            field=models.FloatField(default=0.0),
        ),
    ]
