# Generated by Django 3.2.5 on 2024-01-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='psw',
            field=models.CharField(max_length=64, verbose_name='管理员密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='psw',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
