# Generated by Django 3.2.5 on 2024-04-10 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20240409_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='login_time',
            field=models.DateTimeField(),
        ),
    ]
