# Generated by Django 3.2.5 on 2024-04-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20240410_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='login_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
