# Generated by Django 3.2.5 on 2024-01-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('imdb_id', models.IntegerField()),
                ('duration', models.CharField(blank=True, max_length=256)),
                ('release_time', models.CharField(blank=True, max_length=256)),
                ('intro', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=256)),
                ('writers', models.CharField(blank=True, max_length=256)),
                ('actors', models.CharField(blank=True, max_length=512)),
                ('genre', models.ManyToManyField(to='app01.Genre')),
            ],
            options={
                'db_table': 'tb_movie',
            },
        ),
        migrations.AlterModelTable(
            name='admin',
            table='tb_admin',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='tb_userinfo',
        ),
        migrations.CreateModel(
            name='Movie_similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('movie_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_source', to='app01.movie')),
                ('movie_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_target', to='app01.movie')),
            ],
            options={
                'db_table': 'tb_movie_similarity',
                'ordering': ['-similarity'],
            },
        ),
        migrations.CreateModel(
            name='Movie_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('comment', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.userinfo')),
            ],
            options={
                'db_table': 'tb_movie_ratting',
            },
        ),
        migrations.CreateModel(
            name='Movie_hot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_number', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.movie')),
            ],
            options={
                'db_table': 'tb_movie_hot',
                'ordering': ['-rating_number'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_similarity',
            field=models.ManyToManyField(related_name='_app01_movie_movie_similarity_+', through='app01.Movie_similarity', to='app01.Movie'),
        ),
    ]
